### ISSUE TITLE
CI Artifacts not available for download

### ISSUE THREAD

**Issue by anthonyryan** [george-hopkins/codeplug-prepare#1]
It appears the retention on the build repo is deleting built packages. Any chance we can get a build added to the release tab? I'll attempt to build my own from project but just wanted to post that issue.

https://ci.appveyor.com/project/george-hopkins/codeplug-prepare/builds/13422149/artifacts

**Comment by george-hopkins** [comment]
Thank your for the notification. It looks like Appveyor changed their retention policy for build artifacts.

In case anyone stumbles upon this issue: You can find them on the [releases page](https://github.com/george-hopkins/codeplug-prepare/releases) from now on.
